### ISSUE TITLE
Binder fails to build docker container 

### ISSUE THREAD

**Issue by qwitwa** [criteo-research/iclr_analysis#1]
Fails at 
```
Step 39/44 : RUN conda env update -n root -f "environment.yml" && conda clean -t
```
In particular:

```
==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.6.8

Please update conda by running

    $ conda update -n base conda
```
(then various package installations, edited out here) 
```
Downloading and Extracting Packages
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... failed

ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::qgrid-1.1.1-py37_1001'.
LinkError: post-link script failed for package conda-forge::qgrid-1.1.1-py37_1001
running your command again with `-v` will provide additional information
location of failed script: /srv/conda/bin/.qgrid-post-link.sh
==> script messages <==
<None>
```

The build step fails with non-zero code 1.

**Comment by nd7141** [comment]
Hello @qwitwa 

Thank you for the issue. There is a problem with installing qgrid with conda, so it was changed to install with pip. Now it should work.

**Comment by qwitwa** [comment]
Hmm, qgrid doesn't seem to show anything for me when displayed in binder. I'm just browsing the dataframe instead at the minute.

**Comment by nd7141** [comment]
Hi @qwitwa 

Indeed, the docker image is installed but then the widget is not displayed due to the absence of widget enable (necessary when installed from pip). 

I reproduced an error locally and it seems there is an issue on **qgrid** side. I submitted an issue. 

In the meantime, I found that you can follow a workaround. 

In the very first cell you can add:

```
!jupyter nbextension enable --py --sys-prefix qgrid
!jupyter nbextension enable --py --sys-prefix widgetsnbextension 

```

This will enable widgets. However, you would need to reload your notebook. After that you can run the code as usual. 

I will add this workaround later, while the installation from conda is not fixed.

**Comment by nd7141** [comment]
The issue is fixed. You can launch the latest version of the repo via binder and it will work. Remember that you might need to enable widgets in the first line and then refresh the page and run the code as usual.
